### ISSUE TITLE
`subtract with overflow` panic in `lr_out_of_place_sort`

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Nessex/rdst#11]
I'm sorting a list of 5000 struct elements that implement `RadixKey` as follows:
```rust
#[derive(Debug, Clone, Copy)]
struct IH {
    /// Index in the original text.
    idx: usize,
    /// Hash of a prefix-extension of the suffix starting at `i`.
    h: Mod,
}

/// Sort `IH` by the contained hash.
impl RadixKey for IH {
    const LEVELS: usize = 8;
    #[inline]
    fn get_level(&self, level: usize) -> u8 {
        (self.h.0 >> (level * 8)) as u8
    }
}
```
My tests keep running into this error:
```
thread 'test::random_ssa' panicked at /home/philae/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/rdst-0.20.11/src/sorts/out_of_place_sort.rs:249:9:
attempt to subtract with overflow
stack backtrace:
...
   3: rdst::sorts::out_of_place_sort::lr_out_of_place_sort
             at /home/philae/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/rdst-0.20.11/src/sorts/out_of_place_sort.rs:249:9
   4: rdst::sorts::lsb_sort::<impl rdst::sorter::Sorter>::lsb_sort_adapter
             at /home/philae/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/rdst-0.20.11/src/sorts/lsb_sort.rs:107:21
   5: rdst::sorter::Sorter::run_sort
             at /home/philae/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/rdst-0.20.11/src/sorter.rs:64:37
   6: rdst::sorter::Sorter::handle_chunk
             at /home/philae/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/rdst-0.20.11/src/sorter.rs:148:9
   7: rdst::sorter::Sorter::top_level_director
             at /home/philae/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/rdst-0.20.11/src/sorter.rs:164:9
   8: rdst::radix_sort_builder::RadixSortBuilder<T>::sort
             at /home/philae/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/rdst-0.20.11/src/radix_sort_builder.rs:155:9
   9: ssa::Ssa::new_params::dfs
             at ./src/lib.rs:129:13
```

This doesn't happen for sequences with length up to 4000 though (probably because a different algorithm is used?).

I'm not sure if my data has specific properties. If this is hard to replicate using some random fuzzing I'm happy to attach some data.

**Comment by nessex** [comment]
Apologies for the delay, I've managed to replicate this. It's only possible to trigger this under these conditions using the standard tuner:

 - 5000 to 200,000 items
 - Heavily skewed data at one level (e.g. 4990 items with last byte `0xF`, 10 items with last byte `0x0`)
 - Debug build
 
The subtractions should be harmless in a release build, as while the numbers will wrap, they will not be used again after that point. I run the test suite in release mode because it's too slow otherwise, so didn't encounter this panic while testing sorry.

The 5000 to 200,000 items and skewed data conditions are caused by the standard tuner only using `Algorithm::LrLsb` in that situation.

Still working on the fix, will try to have it out by tomorrow.

**Comment by nessex** [comment]
I've pushed a new version as `0.20.12`. From the tests, it seems the subtractions are all _fine_ (values aren't used after wrapping), it's just the wrapping causing panics in debug. Rather than add a bunch of conditionals, I've explicitly marked these as wrapping / saturating to avoid the panics in debug builds.

Please let me know if this resolves the issue for you!

**Comment by RagnarGrootKoerkamp** [comment]
Thanks for the fix! My tests are passing again :)

Indeed it's not unlikely I was feeding it some kind of skewed data.
